export var themeDefaults = {
    animation: {
        xslow: '',
        slow: '',
        medium: '',
        fast: '',
        easeFast: function () { return ''; },
        easeMedium: function () { return ''; },
        easeSlow: function () { return ''; },
        easeXslow: function () { return ''; },
        easeInFast: function () { return ''; },
        easeInMedium: function () { return ''; },
        easeInSlow: function () { return ''; },
        easeInXslow: function () { return ''; },
        easeInOutFast: function () { return ''; },
        easeInOutMedium: function () { return ''; },
        easeInOutSlow: function () { return ''; },
        easeInOutXslow: function () { return ''; },
    },
    border: {
        none: '',
        rounded: '',
        circle: '',
        style: '',
        dash: '',
        thickWidth: '',
        thickColor: '',
        thinWidth: '',
        thinColor: '',
        thick: '',
        thickInvert: '',
        thickDashed: '',
        thickDashedInvert: '',
        thickTransparent: '',
        thin: '',
        thinDashed: '',
        thinDashedInvert: '',
        thinInvert: '',
        thinTransparent: '',
    },
    color: {
        foreground: '',
        background: '',
        foregroundInvert: '',
        backgroundInvert: '',
        transparent: '',
        outline: '',
        white: '',
        black: '',
        default: '',
        default2: '',
        'default-050': '',
        'default-100': '',
        'default-200': '',
        'default-300': '',
        'default-400': '',
        'default-500': '',
        'default-600': '',
        'default-700': '',
        'default-800': '',
        'default-900': '',
        active: '',
        active2: '',
        'active-050': '',
        'active-100': '',
        'active-200': '',
        'active-300': '',
        'active-400': '',
        'active-500': '',
        'active-600': '',
        'active-700': '',
        'active-800': '',
        'active-900': '',
        accent: '',
        accent2: '',
        'accent-050': '',
        'accent-100': '',
        'accent-200': '',
        'accent-300': '',
        'accent-400': '',
        'accent-500': '',
        'accent-600': '',
        'accent-700': '',
        'accent-800': '',
        'accent-900': '',
        action: '',
        action2: '',
        'action-050': '',
        'action-100': '',
        'action-200': '',
        'action-300': '',
        'action-400': '',
        'action-500': '',
        'action-600': '',
        'action-700': '',
        'action-800': '',
        'action-900': '',
        danger: '',
        danger2: '',
        'danger-050': '',
        'danger-100': '',
        'danger-200': '',
        'danger-300': '',
        'danger-400': '',
        'danger-500': '',
        'danger-600': '',
        'danger-700': '',
        'danger-800': '',
        'danger-900': '',
        warning: '',
        warning2: '',
        'warning-050': '',
        'warning-100': '',
        'warning-200': '',
        'warning-300': '',
        'warning-400': '',
        'warning-500': '',
        'warning-600': '',
        'warning-700': '',
        'warning-800': '',
        'warning-900': '',
        success: '',
        success2: '',
        'success-050': '',
        'success-100': '',
        'success-200': '',
        'success-300': '',
        'success-400': '',
        'success-500': '',
        'success-600': '',
        'success-700': '',
        'success-800': '',
        'success-900': '',
        disabled: '',
        disabled2: '',
        'disabled-050': '',
        'disabled-100': '',
        'disabled-200': '',
        'disabled-300': '',
        'disabled-400': '',
        'disabled-500': '',
        'disabled-600': '',
        'disabled-700': '',
        'disabled-800': '',
        'disabled-900': '',
    },
    elevate: {
        0: '',
        1: '',
        2: '',
        3: '',
        4: '',
        5: '',
        default: '',
    },
    font: {
        color: '',
        colorInvert: '',
        smooth: '',
        code: "'Source Code Pro', 'Consolas', 'Inconsolata', 'Source Code Pro', 'Monaco', monospace !important",
        serif: "'Merriweather','Georgia',serif",
        sans: 'system-ui, -apple-system, Segoe UI, Roboto, Noto Sans, Ubuntu, Cantarell, Helvetica Neue, sans-serif',
        size: {
            1: '12px',
            2: '14px',
            3: '16px',
            4: '18px',
            5: '20px',
            6: '24px',
            7: '30px',
            8: '36px',
            9: '48px',
            10: '60px',
            11: '72px',
            12: '84px',
            default: '16px',
        },
        lineHeight: {
            1: 1,
            2: 1.5,
            3: 1.75,
            4: 2,
            default: 1.75,
        },
        weight: {
            1: 400,
            2: 500,
            3: 600,
            4: 700,
            5: 800,
            6: 900,
            default: 400,
        },
    },
    radius: {
        circle: '',
        none: '',
        round: '',
        rounded: '',
    },
    shared: {},
    scrollbar: {
        width: '',
        height: '',
        backgroundColor: '',
        corner: {
            backgroundColor: '',
        },
        thumb: {
            backgroundColor: '',
            outline: '',
            transition: '',
            hover: {
                backgroundColor: '',
            },
        },
    },
    swatches: {},
};
//# sourceMappingURL=defaults.theme.js.map